# Generated by Django 3.0.7 on 2020-06-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Krolowie',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('imie', models.TextField(verbose_name='Imie króla')),
                ('ppanowanie', models.DateTimeField(verbose_name='Data rozpoczecia panowania')),
                ('kpanowanie', models.DateTimeField(verbose_name='Data zakonczenia panowania')),
            ],
        ),
        migrations.CreateModel(
            name='Moneta',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.TextField(verbose_name='Nazwa monety')),
                ('awers', models.ImageField(upload_to='', verbose_name='Awers')),
                ('rewers', models.ImageField(upload_to='', verbose_name='Rewers')),
                ('panowanie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Krolowie')),
            ],
        ),
    ]
