# Generated by Django 3.0.7 on 2020-06-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynastie',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=70, verbose_name='Imie króla')),
                ('ppanowanie', models.DateTimeField(verbose_name='Data rozpoczecia panowania')),
                ('kpanowanie', models.DateTimeField(verbose_name='Data zakonczenia panowania')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=70, verbose_name='Nazwa materiału')),
                ('chemia', models.CharField(max_length=70, verbose_name='Chemiczne oznaczenie')),
                ('gestosc', models.IntegerField(verbose_name='Gestość w kg/m^3')),
            ],
        ),
        migrations.CreateModel(
            name='Mennica',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=70, verbose_name='Nazwa mennicy')),
                ('lokalizacja', models.CharField(max_length=70, verbose_name='Lokalizacja mennicy')),
            ],
        ),
        migrations.CreateModel(
            name='Rzadkosc',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=70, verbose_name='Nazwa')),
                ('skrot', models.CharField(max_length=10, verbose_name='Skrót')),
            ],
        ),
        migrations.CreateModel(
            name='Stan',
            fields=[
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=70, verbose_name='Nazwa stanu')),
                ('skrot', models.CharField(max_length=10, verbose_name='Skrót')),
            ],
        ),
        migrations.AddField(
            model_name='moneta',
            name='autor',
            field=models.CharField(default=0, max_length=70, verbose_name='autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='cena',
            field=models.IntegerField(default=0, verbose_name='Cena w €'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='rant',
            field=models.ImageField(default=0, upload_to='', verbose_name='Rant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='rok',
            field=models.IntegerField(default=1, verbose_name='Rok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='srednica',
            field=models.IntegerField(default=1, verbose_name='Średnica w cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='waga',
            field=models.IntegerField(default=1, verbose_name='Waga w gramach'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='krolowie',
            name='imie',
            field=models.CharField(max_length=70, verbose_name='Imię króla'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Numer katalogowy'),
        ),
        migrations.AddField(
            model_name='krolowie',
            name='dynastia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Dynastie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='mennica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Mennica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='rzadkosc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Rzadkosc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneta',
            name='stan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Stan'),
            preserve_default=False,
        ),
    ]
