# Generated by Django 3.0.7 on 2020-06-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200623_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneta',
            name='awers',
            field=models.ImageField(null=True, upload_to='', verbose_name='Awers'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='cena',
            field=models.IntegerField(null=True, verbose_name='Cena w €'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Material'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='mennica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Mennica'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='nazwa',
            field=models.TextField(null=True, verbose_name='Nazwa monety'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='panowanie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Krolowie'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rant',
            field=models.ImageField(null=True, upload_to='', verbose_name='Rant'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rewers',
            field=models.ImageField(null=True, upload_to='', verbose_name='Rewers'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rok',
            field=models.IntegerField(null=True, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rzadkosc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Rzadkosc'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='srednica',
            field=models.IntegerField(null=True, verbose_name='Średnica w cm'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='stan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Stan'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='waga',
            field=models.IntegerField(null=True, verbose_name='Waga w gramach'),
        ),
    ]
