# Generated by Django 3.0.7 on 2020-07-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200623_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneta',
            name='opis',
            field=models.CharField(max_length=70, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Material', verbose_name='Materiał'),
        ),
    ]
