# Generated by Django 3.0.7 on 2020-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200705_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneta',
            name='pochodzenie',
            field=models.CharField(max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='cena',
            field=models.FloatField(null=True, verbose_name='Cena katalogowa w €'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='cenaz',
            field=models.FloatField(null=True, verbose_name='Cena zapłacona w zł'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rant',
            field=models.CharField(max_length=70, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='waga',
            field=models.FloatField(null=True, verbose_name='Waga w gramach'),
        ),
    ]
