# Generated by Django 3.0.7 on 2020-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200823_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneta',
            name='autor',
            field=models.CharField(max_length=255, null=True, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='nazwa',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa monety'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='opis',
            field=models.CharField(max_length=255, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rant',
            field=models.CharField(max_length=255, null=True, verbose_name='opis'),
        ),
    ]
