# Generated by Django 3.0.7 on 2020-08-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200823_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynastie',
            name='kpanowanie',
            field=models.IntegerField(verbose_name='Data zakonczenia'),
        ),
        migrations.AlterField(
            model_name='dynastie',
            name='ppanowanie',
            field=models.IntegerField(verbose_name='Data rozpoczecia'),
        ),
        migrations.AlterField(
            model_name='krolowie',
            name='kpanowanie',
            field=models.IntegerField(verbose_name='Data zakonczenia panowania'),
        ),
        migrations.AlterField(
            model_name='krolowie',
            name='ppanowanie',
            field=models.IntegerField(verbose_name='Data rozpoczecia panowania'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='awers',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Awers'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='cena',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena katalogowa w €'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='cenaz',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena zapłacona w zł'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='katalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Katalog', verbose_name='Do jakiego katalogu należy'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Material', verbose_name='Materiał'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='nazwa',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa monety'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='opis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='panowanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Krolowie'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='pochodzenie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rewers',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rewers'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rok',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rok'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='rzadkosc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Rzadkosc'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='srednica',
            field=models.IntegerField(blank=True, null=True, verbose_name='Średnica w mm'),
        ),
        migrations.AlterField(
            model_name='moneta',
            name='stan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Stan'),
        ),
    ]
